[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
s_3_asset_manager_vault = "9S5bjM3yp8RczYd9CPJYXvG3LQ88v5gK6TeG2fraukEm"

[programs.devnet]
s_3_asset_manager_vault = "9S5bjM3yp8RczYd9CPJYXvG3LQ88v5gK6TeG2fraukEm"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
